name: Build Docker Containers
on:

  # You likely want test builds to happen during PR reviews
  pull_request: []

jobs:
  build-images:
    runs-on: ubuntu-latest

    # Define your registry and repository here.
    # These are for the GitHub Container registry, you can also use
    # Quay.io or another OCI registry
    env:
      registry: ghcr.io
      username: autamus
      repository: container-builder-template     

    strategy:

      # A matrix of Dockerfile paths and associated tags
      # Dockerfile in root builds to tag latest
      matrix:
        dockerfile: [[Dockerfile, latest], [subfolder/Dockerfile, subfolder]]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ${{ matrix.dockerfile[1] }}
        run: |
          container="${{ env.registry }}/${{ env.username }}/${{ env.repository }}:${{ matrix.dockerfile[1] }}";
          printf "Preparing to build ${container} from ${{ matrix.dockerfile[0] }}"
          if [ ! -f "${{ matrix.dockerfile[0]}}" ]; then
              printf "Dockerfile ${{ matrix.dockerfile[0]}} does not exist"
              exit 1;
          fi
          docker build -f ${{ matrix.dockerfile[0] }} -t ${container} .
          docker images
